### ISSUE TITLE
Error because of Esm and common js conflict 

### ISSUE THREAD

**Issue by anishdevtech** [M3rcena/m3rcena-weky#2]
**Error**
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/index.js from /data/data/com.termux/files/home/Milanio/src/commands/prefix/Utility/calculator.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead either rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at Object.<anonymous> (/data/data/com.termux/files/home/Milanio/src/commands/prefix/Utility/calculator.js:4:11) {
  code: 'ERR_REQUIRE_ESM'
} Promise {
  <rejected> Error [ERR_REQUIRE_ESM]: require() of ES Module /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/index.js from /data/data/com.termux/files/home/Milanio/src/commands/prefix/Utility/calculator.js not supported.
  index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
  Instead either rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

      at Object.<anonymous> (/data/data/com.termux/files/home/Milanio/src/commands/prefix/Utility/calculator.js:4:11) {
    code: 'ERR_REQUIRE_ESM'
  }
}
```

**Comment by M3rcena** [comment]
@anishdevtech I will take a look when home

**Comment by anishdevtech** [comment]
ermux/files/home/Milanio/node_modules/node-fetch/src/index.js from /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/NeverHaveIEver-BsbfRLP4.cjs not supported.
Instead change the require of index.js in /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/NeverHaveIEver-BsbfRLP4.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/NeverHaveIEver-BsbfRLP4.cjs:4:13) {
  code: 'ERR_REQUIRE_ESM'
} Promise {
  <rejected> Error [ERR_REQUIRE_ESM]: require() of ES Module /data/data/com.termux/files/home/Milanio/node_modules/node-fetch/src/index.js from /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/NeverHaveIEver-BsbfRLP4.cjs not supported.
  Instead change the require of index.js in /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/NeverHaveIEver-BsbfRLP4.cjs to a dynamic import() which is available in all CommonJS modules.
      at Object.<anonymous> (/data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/NeverHaveIEver-BsbfRLP4.cjs:4:13) {
    code: 'ERR_REQUIRE_ESM'                                       }
}
Error [ERR_REQUIRE_ESM]: require() of ES Module /data/data/com.termux/files/home/Milanio/node_modules/node-fetch/src/index.js from /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/WouldYouRather-CBZh1MSy.cjs not supported.
Instead change the require of index.js in /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/WouldYouRather-CBZh1MSy.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/WouldYouRather-CBZh1MSy.cjs:4:13) {
  code: 'ERR_REQUIRE_ESM'
} Promise {
  <rejected> Error [ERR_REQUIRE_ESM]: require() of ES Module /data/data/com.termux/files/home/Milanio/node_modules/node-fetch/src/index.js from /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/WouldYouRather-CBZh1MSy.cjs not supported.
  Instead change the require of index.js in /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/WouldYouRather-CBZh1MSy.cjs to a dynamic import() which is available in all CommonJS modules.
      at Object.<anonymous> (/data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/WouldYouRather-CBZh1MSy.cjs:4:13) {
    code: 'ERR_REQUIRE_ESM'
  }
}
Error [ERR_REQUIRE_ESM]: require() of ES Module /data/data/com.termux/files/home/Milanio/node_modules/node-fetch/src/index.js from /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/GuessThePokemon-BBRrlhRF.cjs not supported.
Instead change the require of index.js in /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/GuessThePokemon-BBRrlhRF.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/GuessThePokemon-BBRrlhRF.cjs:4:13) {
  code: 'ERR_REQUIRE_ESM'
} Promise {
  <rejected> Error [ERR_REQUIRE_ESM]: require() of ES Module /data/data/com.termux/files/home/Milanio/node_modules/node-fetch/src/index.js from /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/GuessThePokemon-BBRrlhRF.cjs not supported.                                                              Instead change the require of index.js in /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/GuessThePokemon-BBRrlhRF.cjs to a dynamic import() which is available in all CommonJS modules.                                                   at Object.<anonymous> (/data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/GuessThePokemon-BBRrlhRF.cjs:4:13) {                                                          code: 'ERR_REQUIRE_ESM'
  }
}
Error: Cannot find module './function-tD1ad7nu.js'
Require stack:                                                  - /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/RockPaperScissors-CWf71zZU.cjs                       - /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/index.cjs                                            - /data/data/com.termux/files/home/Milanio/src/commands/prefix/Utility/calculator.js
- /data/data/com.termux/files/home/Milanio/src/handlers/commands.js                                                             - /data/data/com.termux/files/home/Milanio/src/class/ExtendedClient.js
- /data/data/com.termux/files/home/Milanio/src/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)       at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)               at Object.<anonymous> (/data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/RockPaperScissors-CWf71zZU.cjs:5:17)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {                                                                code: 'MODULE_NOT_FOUND',
  requireStack: [                                                   '/data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/RockPaperScissors-CWf71zZU.cjs',                      '/data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/index.cjs',                                           '/data/data/com.termux/files/home/Milanio/src/commands/prefix/Utility/calculator.js',                                           '/data/data/com.termux/files/home/Milanio/src/handlers/commands.js',
    '/data/data/com.termux/files/home/Milanio/src/class/ExtendedClient.js',
    '/data/data/com.termux/files/home/Milanio/src/index.js'
  ]                                                             } Promise {
  <rejected> Error: Cannot find module './function-tD1ad7nu.js'
  Require stack:                                                  - /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/RockPaperScissors-CWf71zZU.cjs                       - /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/index.cjs                                            - /data/data/com.termux/files/home/Milanio/src/commands/prefix/Utility/calculator.js
  - /data/data/com.termux/files/home/Milanio/src/handlers/commands.js                                                             - /data/data/com.termux/files/home/Milanio/src/class/ExtendedClient.js
  - /data/data/com.termux/files/home/Milanio/src/index.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
      at Module._load (node:internal/modules/cjs/loader:985:27)       at Module.require (node:internal/modules/cjs/loader:1235:19)                                                                    at require (node:internal/modules/helpers:176:18)
      at Object.<anonymous> (/data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/RockPaperScissors-CWf71zZU.cjs:5:17)                                                            at Module._compile (node:internal/modules/cjs/loader:1376:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
      at Module.load (node:internal/modules/cjs/loader:1207:32)
      at Module._load (node:internal/modules/cjs/loader:1023:12)
      at Module.require (node:internal/modules/cjs/loader:1235:19) {                                                                code: 'MODULE_NOT_FOUND',
    requireStack: [                                                   '/data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/RockPaperScissors-CWf71zZU.cjs',                      '/data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/index.cjs',                                           '/data/data/com.termux/files/home/Milanio/src/commands/prefix/Utility/calculator.js',                                           '/data/data/com.termux/files/home/Milanio/src/handlers/commands.js',
      '/data/data/com.termux/files/home/Milanio/src/class/ExtendedClient.js',
      '/data/data/com.termux/files/home/Milanio/src/index.js'
    ]
  }
}                                                               Error: Cannot find module './function-tD1ad7nu.js'
Require stack:                                                  - /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/WillYouPressTheButton-CRm02Ych.cjs                   - /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/index.cjs
- /data/data/com.termux/files/home/Milanio/src/commands/prefix/Utility/calculator.js                                            - /data/data/com.termux/files/home/Milanio/src/handlers/commands.js
- /data/data/com.termux/files/home/Milanio/src/class/ExtendedClient.js                                                          - /data/data/com.termux/files/home/Milanio/src/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)       at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)               at Object.<anonymous> (/data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/WillYouPressTheButton-CRm02Ych.cjs:5:17)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)      at Module.require (node:internal/modules/cjs/loader:1235:19) {                                                                code: 'MODULE_NOT_FOUND',
  requireStack: [                                                   '/data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/WillYouPressTheButton-CRm02Ych.cjs',                  '/data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/index.cjs',                                           '/data/data/com.termux/files/home/Milanio/src/commands/prefix/Utility/calculator.js',
    '/data/data/com.termux/files/home/Milanio/src/handlers/commands.js',
    '/data/data/com.termux/files/home/Milanio/src/class/ExtendedClient.js',                                                         '/data/data/com.termux/files/home/Milanio/src/index.js'
  ]
} Promise {                                                       <rejected> Error: Cannot find module './function-tD1ad7nu.js'
  Require stack:                                                  - /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/WillYouPressTheButton-CRm02Ych.cjs                   - /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/index.cjs
  - /data/data/com.termux/files/home/Milanio/src/commands/prefix/Utility/calculator.js                                            - /data/data/com.termux/files/home/Milanio/src/handlers/commands.js
  - /data/data/com.termux/files/home/Milanio/src/class/ExtendedClient.js                                                          - /data/data/com.termux/files/home/Milanio/src/index.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
      at Module._load (node:internal/modules/cjs/loader:985:27)       at Module.require (node:internal/modules/cjs/loader:1235:19)                                                                    at require (node:internal/modules/helpers:176:18)
      at Object.<anonymous> (/data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/WillYouPressTheButton-CRm02Ych.cjs:5:17)
      at Module._compile (node:internal/modules/cjs/loader:1376:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)                                                            at Module.load (node:internal/modules/cjs/loader:1207:32)       at Module._load (node:internal/modules/cjs/loader:1023:12)      at Module.require (node:internal/modules/cjs/loader:1235:19) {                                                                code: 'MODULE_NOT_FOUND',                                       requireStack: [                                                   '/data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/WillYouPressTheButton-CRm02Ych.cjs',                  '/data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/index.cjs',
      '/data/data/com.termux/files/home/Milanio/src/commands/prefix/Utility/calculator.js',                                           '/data/data/com.termux/files/home/Milanio/src/handlers/commands.js',                                                            '/data/data/com.termux/files/home/Milanio/src/class/ExtendedClient.js',                                                         '/data/data/com.termux/files/home/Milanio/src/index.js'       ]                                                             }
}                                                               Error: Cannot find module './TicTacToe-CWLZJMoT.js'             Require stack:
- /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/index.cjs
- /data/data/com.termux/files/home/Milanio/src/commands/prefix/Utility/calculator.js
- /data/data/com.termux/files/home/Milanio/src/handlers/commands.js                                                             - /data/data/com.termux/files/home/Milanio/src/class/ExtendedClient.js                                                          - /data/data/com.termux/files/home/Milanio/src/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)       at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)               at /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/index.cjs:370:46
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/index.cjs',                                           '/data/data/com.termux/files/home/Milanio/src/commands/prefix/Utility/calculator.js',                                           '/data/data/com.termux/files/home/Milanio/src/handlers/commands.js',                                                            '/data/data/com.termux/files/home/Milanio/src/class/ExtendedClient.js',
    '/data/data/com.termux/files/home/Milanio/src/index.js'
  ]                                                             } Promise {
  <rejected> Error: Cannot find module './TicTacToe-CWLZJMoT.js'
  Require stack:
  - /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/index.cjs
  - /data/data/com.termux/files/home/Milanio/src/commands/prefix/Utility/calculator.js
  - /data/data/com.termux/files/home/Milanio/src/handlers/commands.js
  - /data/data/com.termux/files/home/Milanio/src/class/ExtendedClient.js
  - /data/data/com.termux/files/home/Milanio/src/index.js             at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
      at Module._load (node:internal/modules/cjs/loader:985:27)
      at Module.require (node:internal/modules/cjs/loader:1235:19)
      at require (node:internal/modules/helpers:176:18)
      at /data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/index.cjs:370:46
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    code: 'MODULE_NOT_FOUND',                                       requireStack: [
      '/data/data/com.termux/files/home/Milanio/node_modules/@m3rcena/weky/dist/index.cjs',
      '/data/data/com.termux/files/home/Milanio/src/commands/prefix/Utility/calculator.js',
      '/data/data/com.termux/files/home/Milanio/src/handlers/commands.js',                                                            '/data/data/com.termux/files/home/Milanio/src/class/ExtendedClient.js',
      '/data/data/com.termux/files/home/Milanio/src/index.js'       ]
  }
}
```

**Comment by anishdevtech** [comment]
Doesn't fixed 😅

**Comment by M3rcena** [comment]
> Doesn't fixed 😅

That's interesting 🤔 

@anishdevtech do you have Discord? It would help me resolve this better

**Comment by anishdevtech** [comment]
Yes I have

**Comment by M3rcena** [comment]
@anishdevtech can I have your username so I can follow up with a DM?

**Comment by anishdevtech** [comment]
anish_sharma

**Comment by anishdevtech** [comment]
If you have any server I can join it

**Comment by anishdevtech** [comment]
According to me the main problem is how we import node-fetch or require node-fetch 
There should be separate files for esm and comman is user

**Comment by M3rcena** [comment]
@anishdevtech I don't have a discord server you can join for the package, but I would love it if you can send a DM so I can send you later for testing

**Comment by anishdevtech** [comment]
Yaa my discord username is |anish_sharma` I don't know your

**Comment by M3rcena** [comment]
You already received my request, as Dark Soul

**Comment by anishdevtech** [comment]
Done
